// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/invoice_schema.dart';
import 'database/product_schema.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1004329388879920808),
      name: 'Product',
      lastPropertyId: const obx_int.IdUid(5, 302927830023177140),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8854025945725242781),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3130657030155395166),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7114074483432036571),
            name: 'quantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2830180274474937716),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 302927830023177140),
            name: 'sku',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1202677154673239085),
      name: 'Invoice',
      lastPropertyId: const obx_int.IdUid(6, 6238046495621215829),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7387981302064137279),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 806112301006689338),
            name: 'invoiceNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2963825027891188531),
            name: 'invoiceStatus',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6701397324359910920),
            name: 'customerName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2137482812353037600),
            name: 'invoiceTotal',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6238046495621215829),
            name: 'invoiceCreatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 5392732565937482353),
            name: 'products',
            targetId: const obx_int.IdUid(1, 1004329388879920808))
      ],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 1202677154673239085),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(1, 5392732565937482353),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Product: obx_int.EntityDefinition<Product>(
        model: _entities[0],
        toOneRelations: (Product object) => [],
        toManyRelations: (Product object) => {},
        getId: (Product object) => object.id,
        setId: (Product object, int id) {
          object.id = id;
        },
        objectToFB: (Product object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final skuOffset = fbb.writeString(object.sku);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.quantity);
          fbb.addFloat64(3, object.price);
          fbb.addOffset(4, skuOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final quantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final priceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final skuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = Product(
              id: idParam,
              name: nameParam,
              quantity: quantityParam,
              price: priceParam,
              sku: skuParam);

          return object;
        }),
    Invoice: obx_int.EntityDefinition<Invoice>(
        model: _entities[1],
        toOneRelations: (Invoice object) => [],
        toManyRelations: (Invoice object) =>
            {obx_int.RelInfo<Invoice>.toMany(1, object.id): object.products},
        getId: (Invoice object) => object.id,
        setId: (Invoice object, int id) {
          object.id = id;
        },
        objectToFB: (Invoice object, fb.Builder fbb) {
          final invoiceNumberOffset = fbb.writeString(object.invoiceNumber);
          final invoiceStatusOffset = fbb.writeString(object.invoiceStatus);
          final customerNameOffset = fbb.writeString(object.customerName);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, invoiceNumberOffset);
          fbb.addOffset(2, invoiceStatusOffset);
          fbb.addOffset(3, customerNameOffset);
          fbb.addFloat64(4, object.invoiceTotal);
          fbb.addInt64(5, object.invoiceCreatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final invoiceNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final invoiceStatusParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final customerNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final invoiceTotalParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final invoiceCreatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final object = Invoice(
              invoiceNumber: invoiceNumberParam,
              invoiceStatus: invoiceStatusParam,
              customerName: customerNameParam,
              invoiceTotal: invoiceTotalParam,
              invoiceCreatedAt: invoiceCreatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<Invoice>(object.products,
              store, obx_int.RelInfo<Invoice>.toMany(1, object.id));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// See [Product.id].
  static final id =
      obx.QueryIntegerProperty<Product>(_entities[0].properties[0]);

  /// See [Product.name].
  static final name =
      obx.QueryStringProperty<Product>(_entities[0].properties[1]);

  /// See [Product.quantity].
  static final quantity =
      obx.QueryIntegerProperty<Product>(_entities[0].properties[2]);

  /// See [Product.price].
  static final price =
      obx.QueryDoubleProperty<Product>(_entities[0].properties[3]);

  /// See [Product.sku].
  static final sku =
      obx.QueryStringProperty<Product>(_entities[0].properties[4]);
}

/// [Invoice] entity fields to define ObjectBox queries.
class Invoice_ {
  /// See [Invoice.id].
  static final id =
      obx.QueryIntegerProperty<Invoice>(_entities[1].properties[0]);

  /// See [Invoice.invoiceNumber].
  static final invoiceNumber =
      obx.QueryStringProperty<Invoice>(_entities[1].properties[1]);

  /// See [Invoice.invoiceStatus].
  static final invoiceStatus =
      obx.QueryStringProperty<Invoice>(_entities[1].properties[2]);

  /// See [Invoice.customerName].
  static final customerName =
      obx.QueryStringProperty<Invoice>(_entities[1].properties[3]);

  /// See [Invoice.invoiceTotal].
  static final invoiceTotal =
      obx.QueryDoubleProperty<Invoice>(_entities[1].properties[4]);

  /// See [Invoice.invoiceCreatedAt].
  static final invoiceCreatedAt =
      obx.QueryDateProperty<Invoice>(_entities[1].properties[5]);

  /// see [Invoice.products]
  static final products =
      obx.QueryRelationToMany<Invoice, Product>(_entities[1].relations[0]);
}
